# Mock properties data — temporary until DB is integrated
PROPERTIES = [
    {
        "id": "1",
        "property_code": "AE-CHD-000124",
        "title": "Luxury 4BHK Villa",
        "property_type": "Villa",
        "category": "Luxury",
        "price": 11500000,
        "price_display": "₹1.15 Cr",
        "area": 2100,
        "bedrooms": 4,
        "bathrooms": 3,
        "city": "Chandigarh",
        "locality": "Sector 17",
        "status": "Ready to Move",
        "image_emoji": "🏠",
        "description": "Premium villa with modern amenities in prime location",
    },
    {
        "id": "2",
        "property_code": "AE-MOH-000241",
        "title": "Premium 3BHK Apartment",
        "property_type": "Apartment",
        "category": "Residential",
        "price": 7600000,
        "price_display": "₹76 Lakh",
        "area": 1450,
        "bedrooms": 3,
        "bathrooms": 2,
        "city": "Mohali",
        "locality": "Phase 5",
        "status": "Ready to Move",
        "image_emoji": "🏢",
        "description": "Spacious apartment with excellent connectivity",
    },
    {
        "id": "3",
        "property_code": "AE-CHD-000089",
        "title": "Smart 2BHK Apartment",
        "property_type": "Apartment",
        "category": "Residential",
        "price": 5400000,
        "price_display": "₹54 Lakh",
        "area": 980,
        "bedrooms": 2,
        "bathrooms": 2,
        "city": "Zirakpur",
        "locality": "VIP Road",
        "status": "Under Construction",
        "image_emoji": "🏡",
        "description": "Smart home with modern amenities",
    },
    {
        "id": "4",
        "property_code": "AE-PKL-000412",
        "title": "Residential Plot 250 sq yd",
        "property_type": "Plot",
        "category": "Investment",
        "price": 3800000,
        "price_display": "₹38 Lakh",
        "area": 2250,
        "bedrooms": 0,
        "bathrooms": 0,
        "city": "Panchkula",
        "locality": "Sector 20",
        "status": "Available",
        "image_emoji": "🏘",
        "description": "Prime plot in fast-growing locality",
    },
    {
        "id": "5",
        "property_code": "AE-CHD-000067",
        "title": "Luxury 5BHK Villa",
        "property_type": "Villa",
        "category": "Luxury",
        "price": 24000000,
        "price_display": "₹2.4 Cr",
        "area": 3200,
        "bedrooms": 5,
        "bathrooms": 4,
        "city": "Chandigarh",
        "locality": "Sector 8",
        "status": "Ready to Move",
        "image_emoji": "🏛",
        "description": "Ultra-luxury villa with premium finishes",
    },
    {
        "id": "6",
        "property_code": "AE-MOH-000318",
        "title": "Commercial Office Space",
        "property_type": "Commercial",
        "category": "Commercial",
        "price": 9500000,
        "price_display": "₹95 Lakh",
        "area": 1800,
        "bedrooms": 0,
        "bathrooms": 2,
        "city": "Mohali",
        "locality": "IT City",
        "status": "Ready to Move",
        "image_emoji": "🏢",
        "description": "Ideal office space in IT hub",
    },
]